version: '3'
services:
  test:
    build: 
      context: .
      args:
        GITHUB_TOKEN: "${BUILD_GITHUB_TOKEN}"
    command: go test ./...
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - LOG_LEVEL=DEBUG
      - LOG_FORMAT=text
      - DATA_SOURCE_NAME=postgres://postgres:postgres@db:5432/gorest?sslmode=disable
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gorest
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: